import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Header } from '../src/components/blocks/Header';
import { Container } from 'react-bootstrap';
import { Button } from '../src/components/elements/Button';
import { Page } from '../src/components/layout/Page';
import cls from 'classnames';

import styles from '../styles/Page404.module.scss';

const Page404: NextPage = () => {
  return (
    <div>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page img={'./assets/shop-detail-banner.jpg'} title="404">
      <section className={cls("text-center", styles.pt_100)} >
        <Container>
          <div className={styles.root}>
            <div className={styles.main_text}>404</div>
            <h2 className="mb-30" style={{ marginBottom: '30px' }}>
              Ooops! 404 - Page Not Found
            </h2>
            <Button text='back to home' type='color' />
          </div>
        </Container>
      </section>
      </Page>
    </div>
  );
};

export default Page404;
