import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Col, Container, Form, Row, Table, FormControl } from 'react-bootstrap';
import cls from 'classnames';

import { Button } from '../src/components/elements/Button';
import { Page } from '../src/components/layout/Page';
import { userService } from '../src/services/user';

import styles from '../styles/Cart.module.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faShoppingCart, faTrash } from '@fortawesome/free-solid-svg-icons';
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from 'src/redux/store';
import { IProduct, IUser } from 'src/models';
import {
  removeFromCart,
  plusItemCart,
  minusItemCart,
  clearCart,
} from 'src/redux/slice';
import { orderService } from 'src/services/order';

const Cart: NextPage = () => {
  const dispatch = useDispatch();
  const [user, setUser] = useState<IUser>();
  const [comment, setComment] = useState<string>('');
  const router = useRouter();
  const { order } = useSelector((state: RootState) => state.basket);

  const counterPlus = (item: IProduct) => {
    dispatch(plusItemCart(item.id!));
  };

  const counterMinus = (item: IProduct) => {
    dispatch(minusItemCart(item.id!));
  };

  const handleRemove = (item: IProduct) => {
    dispatch(removeFromCart(item));
  };

  const handleChange = (e) => {
    if (e.target.value) {
      setComment(e.target.value);
    }
  };

  const onSubmit = () => {
    if (!userService.userValue) {
      router.push('/login');
    }

    if (order.items.length > 0) {
      orderService
        .create({
          ...order,
          id_user: user?.id,
          create_time: Math.floor(Date.now() / 1000),
          comment,
        })
        .then(() => {
          dispatch(clearCart());
          alert('Success');
        });
    }
  };

  useEffect(() => {
    const subscription = userService.user.subscribe((x) => setUser(x));
    return () => subscription.unsubscribe();
  }, []);

  return (
    <div>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page img={'./assets/shop-detail-banner.jpg'} title="Cart">
        <section className={cls(styles.pt_100, styles.mb_50)}>
          <Container>
            <div className={styles.wishlist_table}>
              <div className={styles.responsive_table}>
                {order.items.length === 0 ? (
                  <h1>The cart is empty :(</h1>
                ) : (
                  <table
                    className={cls(
                      styles.table,
                      styles.border,
                      styles.text_center
                    )}
                  >
                    <thead>
                      <tr>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Sub Total</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {order.items.map((e) => (
                        <tr key={e.id}>
                          <td className={styles.text_left}>
                            <div
                              className={cls(
                                styles.seller_box,
                                styles.align_flax,
                                styles.w_100
                              )}
                            >
                              <div className={styles.seller_img}>
                                <a href="#" className={styles.display_b}>
                                  <img
                                    src={e.img}
                                    alt="shoes"
                                    className={styles.transition}
                                  />
                                </a>
                              </div>
                              <div
                                className={cls(
                                  styles.seller_contain,
                                  styles.pl_15
                                )}
                              >
                                <a
                                  href="#"
                                  className={cls(
                                    styles.product_name,
                                    styles.text_uppercase
                                  )}
                                >
                                  {e.name}
                                </a>
                              </div>
                            </div>
                          </td>
                          <td>
                            <span className={styles.price}>$ {e.price}</span>
                          </td>
                          <td>
                            <div
                              className={cls(styles.table_listing, styles.qty)}
                            >
                              <div className={styles.quantity_input}>
                                <button
                                  className={cls(
                                    styles.quantity_input__modifier,
                                    styles.quantity_input__modifier__left
                                  )}
                                  onClick={() => counterMinus(e)}
                                >
                                  &mdash;
                                </button>
                                <input
                                  className={styles.quantity_input__screen}
                                  type="text"
                                  value={e.count}
                                />
                                <button
                                  className={cls(
                                    styles.quantity_input__modifier,
                                    styles.quantity_input__modifier__right
                                  )}
                                  onClick={() => counterPlus(e)}
                                >
                                  &#xff0b;
                                </button>
                              </div>
                            </div>
                          </td>
                          <td>
                            <span className={styles.price}>
                              $ {e.price * e.count}
                            </span>
                          </td>
                          <td>
                            <ul>
                              <li>
                                <a href="#">
                                  <FontAwesomeIcon
                                    icon={faTrash}
                                    onClick={() => handleRemove(e)}
                                  />
                                </a>
                              </li>
                            </ul>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>
              <Row>
                <Col md={6}>
                  <div className={cls(styles.share_wishlist)}>
                    <Button text="Continue Shopping" />
                  </div>
                </Col>
                {/* <Col md={6}>
                  <div className={cls(styles.shoping_con)}>
                    <Button text="Update Cart" />
                  </div>
                </Col> */}
              </Row>
              <div className={styles.estimate}>
                <Row>
                  <Col md={6}>
                    <h2 className={cls(styles.reviews_head, styles.pb_20)}>
                      Estimate shipping and tax
                    </h2>
                    <Form className={styles.main_form}>
                      <Row>
                        <Col xs={12}>
                          <Form className={styles.form_group}>
                            <FormControl
                              as="textarea"
                              rows={6}
                              value={comment}
                              className={styles.form_control}
                              placeholder="Enter message:"
                              onChange={handleChange}
                            ></FormControl>
                          </Form>
                        </Col>
                        {/* <Col xs={12}>
                          <div className={styles.form_group}>
                            <select className={styles.form_control}>
                              <option value="">Select Country</option>
                              <option value="1">India</option>
                              <option value="2">China</option>
                              <option value="3">Pakistan</option>
                            </select>
                          </div>
                        </Col>
                        <Col md={6}>
                          <div className={styles.form_group}>
                            <select className={styles.form_control}>
                              <option value="">Select State/Province</option>
                              <option value="1">India</option>
                              <option value="2">China</option>
                              <option value="3">Pakistan</option>
                            </select>
                          </div>
                        </Col>
                        <Col md={6}>
                          <div className={styles.form_group}>
                            <select className={styles.form_control}>
                              <option value="">Select City</option>
                              <option value="1">India</option>
                              <option value="2">China</option>
                              <option value="3">Pakistan</option>
                            </select>
                          </div>
                        </Col>
                        <Col md={6}>
                          <Button type="color" text="Calculat" />
                        </Col> */}
                      </Row>
                    </Form>
                  </Col>
                  <Col md={6}>
                    <div className={styles.cart_total_table}>
                      <div className={styles.responsive_table}>
                        <table className={cls(styles.table, styles.border)}>
                          <thead>
                            <tr>
                              <th colSpan={2}>Cart Total</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>Item(s) Subtotal</td>
                              <td>
                                <div className={styles.price_box}>
                                  <span className={styles.price}>
                                    $ {order.price}
                                  </span>
                                </div>
                              </td>
                            </tr>
                            <tr>
                              <td>Shipping</td>
                              <td>
                                <div className={styles.price_box}>
                                  <span className={styles.price}>$0.00</span>
                                </div>
                              </td>
                            </tr>
                            <tr>
                              <td className={styles.payable}>
                                <b>Amount Payable</b>
                              </td>
                              <td>
                                <div className={styles.price_box}>
                                  <span className={styles.price}>
                                    $ {order.price}
                                  </span>
                                </div>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                      <div className={styles.shoping_con}>
                        <Button
                          type="color"
                          text="Proceed to checkout"
                          onClick={onSubmit}
                        />
                      </div>
                    </div>
                  </Col>
                </Row>
              </div>
            </div>
          </Container>
        </section>
      </Page>
    </div>
  );
};
export default Cart;
