import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup/dist/yup';
import * as Yup from 'yup';
import { Col, Container, Form, Row } from 'react-bootstrap';
import cls from 'classnames';
import { UserCredential } from 'firebase/auth';

import { Button } from '../src/components/elements/Button';
import { Page } from '../src/components/layout/Page';
import { userService } from '../src/services/user';

import styles from '../styles/Login.module.scss';
import { firebase } from 'src/services/firebase';
import { TextInput } from 'src/components/form_fields/TextInput';
import { Checkbox } from 'src/components/form_fields/Checkbox';

const Login: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    // redirect to home if already logged in
    if (userService.userValue) {
      router.push('/');
    }
  }, []);

  // form validation rules
  const validationSchema = Yup.object().shape({
    email: Yup.string().required('Email is required'),
    password: Yup.string().required('Password is required'),
  });
  const formOptions = { resolver: yupResolver(validationSchema) };

  // get functions to build form with useForm() hook
  const { handleSubmit, setError, formState, control } = useForm(formOptions);

  const onSubmit = ({
    email,
    password,
  }: {
    email: string;
    password: string;
  }) => {
    return firebase
      .login(email, password)
      .then((userCredential: UserCredential) => {
        const { uid } = userCredential.user;
        return uid;
      })
      .then((uid) => {
        userService
          .login(email, uid)
          .then(() => {
            // get return url from query parameters or default to '/'
            // TODO string[] || string
            const returnUrl = router.query.returnUrl || '/cabinet';
            router.push(returnUrl as string);
          })
          .catch((error) => {
            setError('apiError', { message: error.message || error });
          });
      });
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page img={'./assets/checkout-banner.jpeg'} title="Login">
        <section className={cls(styles.root, styles.pt_100)}>
          <Container>
            <div className={styles.wrapper}>
              <h2 className="text-center text-uppercase">Customer Login</h2>
              <Form onSubmit={handleSubmit(onSubmit)}>
                <TextInput
                  name="email"
                  control={control}
                  rules={{ required: true }}
                  className={styles.form_control}
                  label={'Email address'}
                  placeholder={'Enter your email'}
                  // type="email"
                  type="text"
                />

                <TextInput
                  name="password"
                  control={control}
                  rules={{ required: true }}
                  className={styles.form_control}
                  label={'Email address'}
                  placeholder={'Enter your password'}
                  type="password"
                />

                <div className={styles.login_btn_g}>
                  <Row>
                    <Col xs={6}>
                      <Checkbox
                        name="remember"
                        control={control}
                        className={styles.form_control}
                        label={'Remember Me'}
                      />
                    </Col>
                    <Col xs={6}>
                      <Button
                        text="Log in"
                        type="color"
                        className={styles.btn}
                      />
                    </Col>
                  </Row>
                </div>
                <div className="text-center">
                  <a title="Forgot Password" className={styles.link} href="#">
                    Forgot your password?
                  </a>
                </div>
                <div className={cls(styles.new_account, 'text-center')}>
                  <span>Don&apos;t have an account?</span>
                  <Link href="/register">
                    <a id="Create New Account" className={styles.link}>
                      {' '}
                      Create New Account
                    </a>
                  </Link>
                </div>
              </Form>
            </div>
          </Container>
        </section>
      </Page>
    </div>
  );
};
export default Login;
