import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import {
  Col,
  Container,
  Form,
  Row,
  Pagination,
  Spinner,
} from 'react-bootstrap';
import cls from 'classnames';

import { Category } from '../src/components/blocks/Category';
import { Filter } from '../src/components/blocks/Filter';
import { ProductCard } from '../src/components/elements/ProductCard';
import { PaginationBase } from '../src/components/blocks/PaginationBase';

import { Button } from '../src/components/elements/Button';
import { Page } from '../src/components/layout/Page';
import { userService } from '../src/services/user';

import styles from '../styles/Shop.module.scss';
import { productService } from 'src/services/product';
import { IProduct } from 'src/models';

const Shop: NextPage = () => {
  const router = useRouter();
  const { categories, prices } = router.query;
  const [products, setProducts] = useState<IProduct[] | null>(null);

  useEffect(() => {
    productService.getAll(categories, prices).then((x) => setProducts(x));
  }, []);

  return (
    <div>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page img={'./assets/checkout-banner.jpeg'} title="Shop">
        <section className={cls(styles.pt_100)}>
          <Container>
            <Row>
              <Col xl={4} lg={4} xs={12}>
                <div className={styles.sidebar}>
                  <Category />
                  <Filter />
                </div>
              </Col>
              <Col xl={8} lg={8} xs={12}>
                <div className={cls(styles.shorting, styles.mb_30)}>
                  <Row className={styles.align_flex}>
                    <Col xl={5} lg={5} md={6} className={styles.mb_r_15}>
                      <div className={styles.view}></div>
                      <div className={styles.short_by}>
                        <span>Product Compare (0)</span>
                      </div>
                    </Col>
                    <Col
                      xl={7}
                      lg={7}
                      md={6}
                      className={cls(styles.text_right, styles.text_left_md)}
                    >
                      <div className={styles.show_item}>
                        <span className={styles.ml_0}>Sort By:</span>
                        <div className={styles.select_item}>
                          <select className={styles.m_w_130}>
                            <option value="">Default sorting</option>
                            <option value="">Sort by popularity</option>
                            <option value="">Sort by average rating</option>
                          </select>
                        </div>
                      </div>
                      <div
                        className={cls(styles.show_item, styles.float_right_md)}
                      >
                        <span>Show</span>
                        <div className={styles.select_item}>
                          <select>
                            <option value="">15</option>
                            <option value="">12</option>
                            <option value="">6</option>
                          </select>
                        </div>
                      </div>
                    </Col>
                  </Row>
                </div>
                <div className={styles.featured}>
                  <Row>
                    {!products ? (
                      <Spinner animation="border" />
                    ) : (
                      products.map((e) => (
                        <ProductCard type="shoper" key={e.id} {...e} />
                      ))
                    )}
                  </Row>
                </div>
                <PaginationBase />
              </Col>
            </Row>
          </Container>
        </section>
      </Page>
    </div>
  );
};
export default Shop;
