import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../src/components/blocks/Header'
import { Banner } from '../src/components/blocks/Banner'
import { Featured } from '../src/components/blocks/Featured'
import { Products } from '../src/components/blocks/Products'
import { Sale } from '../src/components/blocks/Sale'
import { BackCall } from '../src/components/blocks/BackCall'
import { Footer } from '../src/components/blocks/Footer'
import 'bootstrap/dist/css/bootstrap.min.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Banner/>
      <Featured/>
      <Products/>
      <Sale/>
      <BackCall/>
      <Footer/>
      
    </div>
  )
}

export default Home
